version: '3.9'

services:
  veslo.postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: "name"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "dbname"
    ports:
      - 5432:5432
    volumes:
      - /home/user/pgdata/veslo.postgres:/var/lib/postgresql/data

  veslo.pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: veslo.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "name@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - 8082:80

  veslo.redis:
    image: redis/redis-stack:7.2.0-v10
    restart: always
    ports:
      - 6379:6379
      - 8001:8001

  veslo.backend:
    image: veslo.backend
    restart: always
    ports:
      - "3003:3003"
    env_file:
      - ./backend-veslo/.env
    depends_on:
      - veslo.postgres
      - redis
    
  veslo.frontend:
    image: veslo.frontend
    restart: always
    ports:
      - "80:3100"
    depends_on:
      - veslo.backend

volumes:
  veslo.postgres:

